### ISSUE TITLE
Could not get behaviour information for: %UndefinedFunctionError{}

### ISSUE THREAD

**Issue by benvp** [oltarasenko/crawly#127]
Hey, 

when including crawly I got a huge amount debug messages like this:

````
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_pool_handler, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_request, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_response, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_socks5, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_ssl, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_ssl_certificate, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_stream, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_sup, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_tcp, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_trace, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_url, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :hackney_util, reason: nil}
[debug] Could not get behaviour information for: %UndefinedFunctionError{arity: 1, function: :__info__, message: nil, module: :epipe, reason: nil}
````

I don't think it's an issue for getting crawly to work, I'm just wondering why I get such an incredible amount of debug messages. 🙂 

Using:
* Elixir v1.11.0
* Erlang 23.1.1
* Crawly 0.11

**Comment by oltarasenko** [comment]
Oh yes. I am now suffering from it as well. Will remove this: https://github.com/oltarasenko/crawly/blob/5867f1622f3af5f0f8bbd539a88e14cf04425ba7/lib/crawly/utils.ex#L170
As it's too noisy. Sorry for it!

**Comment by oltarasenko** [comment]
@benvp Thanks for the feedback. Really happy to know that it's being useful for someone!

**Comment by sandromehic** [comment]
I've got the same messages showing up, and they actually take some time. I have noticed that after adding `crawly` as a dependency the startup time of the application has gone up, and also the execution of tests. On a clean phoenix project `mix test` goes from around 1.5s on my machine, to 6s after just adding crawly and not changing any of the code or adding any tests.

I quickly tried removing the debug message from `deps`, but the startup procedure of crawly in general seems to be affecting these times. I didn't want to open a new issue, since you might already be aware of this, or it is not a problem for most people.

If you need further information let me know.

**Comment by oltarasenko** [comment]
> I've got the same messages showing up, and they actually take some time. I have noticed that after adding `crawly` as a dependency the startup time of the application has gone up, and also the execution of tests. On a clean phoenix project `mix test` goes from around 1.5s on my machine, to 6s after just adding crawly and not changing any of the code or adding any tests.
> 
> I quickly tried removing the debug message from `deps`, but the startup procedure of crawly in general seems to be affecting these times. I didn't want to open a new issue, since you might already be aware of this, or it is not a problem for most people.
> 
> If you need further information let me know.

Hey @sandromehic the related fix is in master. I am preparing a new release right now (developing some features requested by other people). I think I will do a roll out in a few days. Sorry, probably it took longer than it should, but the issue will go away soon.

**Comment by sandromehic** [comment]
great news! 

What about the startup time of crawly? Is it a problem other are also having? It seems strange to me that by just adding crawly on my machine the startup time (and `mix test`) goes from 1.5s to 6s. Granted, with a complete test suite and live reloading, this is a minor issue and it won't impact the times that much, but might be worth investigating why the startup times are so high.

**Comment by Ziinc** [comment]
@sandromehic the increase in startup time it is relating to the current way that crawly discovers spiders that implement the `Crawly.Spider` behaviour. There are some optimizations that we could do for it, such as excluding dependencies from the discovery process. That deserves a separate issue

**Comment by sandromehic** [comment]
ok, I imagined it was something like that. I didn't want to open a new issue, since I was not sure you would consider it a problem and if it should be addressed. Since it's an optimization thing, I'll leave the decision to you whether you want to treat it through github issues. 

Hope I was helpful in bringing this up. Thank you for the responses.

**Comment by oltarasenko** [comment]
@sandromehic In general the situation should improve quite a bit after the release (or if you try with master branch). As @Ziinc has mentioned the operation of getting the list of spiders is not cheap at all. But debug logs made it much worse.

Otherwise it may also depend on the size of your project. E.g. if Crawly is used with other apps (big number of apps for example), the list operation may be quite expensive.

If the start time will stay big after the release I will consider future optimization of the code. (One of the option is to have pre-defined spiders dir, same as with Scrapy). Please let me know.

**Comment by oltarasenko** [comment]
This issue should be resolved now after the release rolled out yesterday.
