### ISSUE TITLE
Read request settings from middlewares

### ISSUE THREAD

**Issue by oltarasenko** [oltarasenko/crawly#50]
Currently, we're setting proxy and follow redirect settings directly, for example:

- https://github.com/oltarasenko/crawly/blob/945acbb1f0db1ace8464d4e6f436375002d1482f/lib/crawly.ex#L15
- https://github.com/oltarasenko/crawly/blob/6d0f9117aabce1e281240a7e7300cdf934affe09/lib/crawly/worker.ex#L139

Check if it's possible to migrate it to middlewares.

**Comment by Ziinc** [comment]
I've got a custom proxy middleware that follows the HTTPoison's format of setting auth (proxy endpoint and auth are separate keywords.

The proxy auth implementation that you had added wasn't sufficient because HTTPoison doesn't recognize proxy auth in the usual http://user:pass@host:port format 

When I've got time I'll abstract it out from my codebase and open a PR

**Comment by oltarasenko** [comment]
Done
