### ISSUE TITLE
I would like to contribute to this project

### ISSUE THREAD

**Issue by michaltrzcinka** [oltarasenko/crawly#83]
Hello,
I've learned the basics of Elixir and OTP and created an online card game with Phoenix (including sockets, channels and presence). I'd like to contribute to this project to gain more experience in Elixir. 
Do you have any task I could help with? I've seen on your roadmap that you want a UI for jobs management, seems like an interesting feature to build.

**Comment by oltarasenko** [comment]
Hi @michaltrzcinka you're more than welcome to contribute! The current roadmap is almost implemented, and I am currently thinking of the new targets.
Also, the UI part for jobs management is currently in the "almost-ready" state, and I will invite you to it separately (hopefully in a couple of weeks from now).

So at this point I would want to suggest the following directions:
1) Follow the tutorial at https://hexdocs.pm/crawly/0.9.0/tutorial.html#content and fix all parts where it's inaccurate in the documentation
2) Update all the example projects listed under https://github.com/oltarasenko/crawly#example-projects so they use the most recent version of Crawly.
3) Review tests. Some of them are failing because of race conditions, some of them just need to be rewritten (e.g. tests are our weak point and some of them are quite bad). Try to increase the code coverage to 100%.
4) Benchmarking - we can discuss it separately. But it would be great to build benchmarks for Crawly to have a better understanding of the performance of the platform. And maybe to compare it with other engines like Scrapy.
5) Implement the download files middleware: https://github.com/oltarasenko/crawly/issues/77
6) Extend the sample projects with couple of your own projects (with a focus on browser rendering (e.g. dynamic websites) or sites with login forms). Here it would be nice to build something like automatic login logic.

Hopefully, any of these topics might be interesting for you. Let me know if it's the case and if you need help.

**Comment by michaltrzcinka** [comment]
Hi @oltarasenko, thanks for all the tips. I will start with the first 2-3 tasks, they look like a great way to get started.

**Comment by michaltrzcinka** [comment]
Concerning point 2, I'm wondering if maybe we could merge all these four repositories with examples into one? It will be easier to maintain and use.

**Comment by oltarasenko** [comment]
Yes, that sounds good. Maybe we don't need that many similar examples as well.

**Comment by Ziinc** [comment]
You could place the examples in an examples dir in this repo to keep everything in sync

**Comment by michaltrzcinka** [comment]
@Ziinc I went with moving everything into https://github.com/oltarasenko/crawly-spider-example
Please check out my PR https://github.com/oltarasenko/crawly-spider-example/pull/4
Maybe we could rename the repo to `crawly-examples`?

**Comment by oltarasenko** [comment]
@michaltrzcinka I wonder if you are available to create a few extra spiders for the CrawlyUI demo (https://github.com/oltarasenko/crawly_ui/tree/master/examples)? For now I have just one Walmart, but I would love to have few other sites added to the list. Is that something I can ask you to take a look on?

**Comment by michaltrzcinka** [comment]
Hi, I just started a new job and won’t be able to help any time soon...

**Comment by oltarasenko** [comment]
Ok, that's great! My congratulations! 

In this case, I wish you all the best with the job, and I want to thank you for contributions!

**Comment by michaltrzcinka** [comment]
Thank you :) I would like to come back and help you out, but this can happen probably in a few months.
